// supabase/functions/send-push/index.ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import webpush from "npm:web-push";

// 1. Configure Web-Push with your local environment variables
const VAPID_PUBLIC_KEY = Deno.env.get("VAPID_PUBLIC_KEY") || "";
const VAPID_PRIVATE_KEY = Deno.env.get("VAPID_PRIVATE_KEY") || "";
const M_EMAIL = Deno.env.get("M_EMAIL") || "mailto:your-email@example.com";

webpush.setVapidDetails(
  M_EMAIL,
  VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY,
);

Deno.serve(async (req) => {
  try {
    // 2. Parse the custom title and body sent to this function
    // Fallback to defaults if no body is passed
    const { title, body } = await req.json().catch(() => ({
      title: "Hello from Local Supabase!",
      body: "This is a test push notification.",
    }));

    // 3. Initialize Supabase Client using internal system keys
    const supabaseUrl = Deno.env.get("SUPABASE_URL") ??
      "http://127.0.0.1:50021";
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // 4. Fetch all active device subscriptions from your database
    const { data: devices, error: dbError } = await supabase
      .from("push_subscriptions")
      .select("id, subscription");

    if (dbError) throw dbError;

    if (!devices || devices.length === 0) {
      return new Response(
        JSON.stringify({ message: "No registered devices found." }),
        { headers: { "Content-Type": "application/json" }, status: 200 },
      );
    }

    // 5. Construct the payload string the Service Worker expects
    const pushPayload = JSON.stringify({ title, body });

    // 6. Loop through all registered devices and fire off the pushes in parallel
    const pushPromises = devices.map(async (device) => {
      try {
        // webpush expects the exact JSON object generated by the browser
        await webpush.sendNotification(device.subscription, pushPayload);
        return { id: device.id, status: "success" };
      } catch (err) {
        console.error(`Failed sending to device ${device.id}:`, err);

        // Clean up: If the token is expired/invalid (status 410 or 404), delete it from DB
        if (err.statusCode === 410 || err.statusCode === 404) {
          await supabase.from("push_subscriptions").delete().eq(
            "id",
            device.id,
          );
        }
        return { id: device.id, status: "failed", error: err.message };
      }
    });

    const results = await Promise.all(pushPromises);

    return new Response(
      JSON.stringify({ message: "Push processing complete", results }),
      { headers: { "Content-Type": "application/json" }, status: 200 },
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { headers: { "Content-Type": "application/json" }, status: 500 },
    );
  }
});
